/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, PerspectiveCamera } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/cellmine-scene.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[10.183, 6.093, 11.042]} rotation={[1.242, 0.33, -0.76]}>
        <PerspectiveCamera
          makeDefault={false}
          far={60.8}
          near={0.1}
          fov={22.895}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Laks_et_Al_2019.geometry}
        material={materials["Material.003"]}
        position={[-1.072, 1.49, 2.269]}
        rotation={[1.572, 0.104, -0.766]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text.geometry}
        material={materials["Material.005"]}
        position={[-4.123, -0.161, 5.084]}
        rotation={[1.515, 0.109, -0.794]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Material.001"]}
        position={[-4.676, 0.954, 0.583]}
        rotation={[0, 0, -1.132]}
        scale={[7.286, 1, 7.921]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Material.002"]}
        position={[-4.676, 0.954, 0.583]}
        rotation={[0, 0, -1.132]}
        scale={[7.286, 1, 7.921]}
      />
    </group>
  );
}

useGLTF.preload("/cellmine-scene.glb");
